export const HTTP_STATUS_CODE = {
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const TRANSIENT_HTTP_STATUS_CODES: readonly number[] = [
  HTTP_STATUS_CODE.BAD_GATEWAY,
  HTTP_STATUS_CODE.SERVICE_UNAVAILABLE,
  HTTP_STATUS_CODE.GATEWAY_TIMEOUT,
];
